name: 'setup'
description: 'Setup environment for dgcode'
inputs:
  PYTHON_VERSION:
    description: Python version to set up
    type: string
    default: '3.8'
  DO_DGBUILD:
    description: Option to turn off tailing dgbuild
    type: boolean
    default: true
  PROJECTS_DIR:
    description: Directory to build the framework in (must include a bootstrap script)
    required: true
    type: string
  DGBUILD_FLAG:
    description: build flag (e.g. 'debug' or 'release')
    type: string
    default: examine

runs:
  using: "composite"
  steps:
    - name: Checkout dgcode framework
      uses: actions/checkout@v2
      with:
        repository: MilanKlausz/devDgcode
        path: './dgcode_framework'
    
    - name: Set up Python (on Linux)
      if: runner.os == 'Linux'
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Get OS version for caches
      id: os-version
      uses: sersoft-gmbh/os-version-action@v1
      
    - name: Get Python version for caches
      id: python-version
      run: echo "::set-output name=version::$(python3 -V | sed -e 's/ /-/g')"
      shell: bash
  
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ runner.os }}
      shell: bash
    
    - name: cache dgdepfixer install
      id: cache-dgdepfixer
      uses: actions/cache@v2
      with:
        path: dgdepfixerInstall
        key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{env.CC}}-${{steps.python-version.outputs.version}}-dgdepfixer-install-20220607
     
    - name: Create dgdepfixer
      if: steps.cache-dgdepfixer.outputs.cache-hit != 'true'
      run: python3 $GITHUB_WORKSPACE/dgcode_framework/.system/depfix/src/__main__.py --create -d $GITHUB_WORKSPACE/dgdepfixerInstall
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash
      
    - name: cache Geant4
      id: cache-geant4
      uses: actions/cache@v2
      with:
        path: geant4-10.04.p03
        key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{env.CC}}-Geant4--nodata-20220607
        
    - name: Install Geant4
      if: steps.cache-geant4.outputs.cache-hit != 'true'
      run: |
        . $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
        dgdepfixer --instsw=Geant4 --nodata -d $GITHUB_WORKSPACE/geant4-10.04.p03
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash
      
    - name: cache untarred geant4 data files
      id: cache-untarred-geant4-data-files
      uses: actions/cache@v2
      with:
        path: Geant4data
        key: untarred-geant4-data-files 
 
    - name: Download Geant4 data
      if: steps.cache-geant4.outputs.cache-hit != 'true' || steps.cache-untarred-geant4-data-files.outputs.cache-hit != 'true'
      run: |
        chmod +x $GITHUB_WORKSPACE/.github/scripts/geant4DataProvider.sh
        $GITHUB_WORKSPACE/.github/scripts/geant4DataProvider.sh
      shell: bash

    - name: Set Geant4 env vars
      run: . $GITHUB_WORKSPACE/.github/scripts/geant4DataSetup.sh
      shell: bash
      
    - name: build framework
      if: inputs.DO_DGBUILD == 'true'
      run: |
        . $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
        . bootstrap.sh
        python3 -c "import matplotlib.pyplot"
        dgbuild -a --${{ inputs.DGBUILD_FLAG }}
      working-directory: ${{ inputs.PROJECTS_DIR }}
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash