name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    default: ubuntu-latest
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - run: echo Will run on ${{ inputs.runs-on }}.
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1
    - run: mkdir $HOME/actionCreatedDirectoryInHome
      shell: bash
    - run: mkdir $GITHUB_WORKSPACE/actionCreatedDirectoryInGHWS
      shell: bash
    - run: echo ${{ runner.os }}
      shell: bash
      
    - name: apt-get pre-reqs for Ubuntu
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update 
        sudo apt-get install curl g++ build-essential python3-dev cmake libxerces-c-dev libexpat1-dev gfortran libhdf5-serial-dev git python3-venv python3-pip python3-tk mesa-common-dev libglu1-mesa-dev freeglut3-dev cm-super 
      
    - name: brew pre-reqs for MacOS
      if: runner.os == 'macOS'
      run: brew install cmake python python-tk expat xerces-c git hdf5 freetype
    
    
