name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    default: ubuntu-latest
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - run: echo Will run on ${{ inputs.runs-on }}.
      env:
        DGDEP_IGNOREBADSHEBANG: 1
    - run: mkdir $HOME/actionCreatedDirectoryInHome
    - run: mkdir $GITHUB_WORKSPACE/actionCreatedDirectoryInGHWS
    #- id: random-number-generator
    #  run: echo "::set-output name=random-id::$(echo $RANDOM)"
    #  shell: bash
    #- run: ${{ github.action_path }}/goodbye.sh
    #  shell: bash
