name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    default: ubuntu-20.04
#outputs:
#  random-number:
#    description: "Random number"
#    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: "composite"
  steps:
    - run: echo Will run on ${{ inputs.runs-on }}.
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1
    - run: mkdir $HOME/actionCreatedDirectoryInHome
      shell: bash
    - run: mkdir $GITHUB_WORKSPACE/actionCreatedDirectoryInGHWS
      shell: bash
      
    - name: apt-get pre-reqs for Ubuntu
      run: |
        sudo apt-get update 
        sudo apt-get install curl g++ build-essential python3-dev cmake libxerces-c-dev libexpat1-dev gfortran libhdf5-serial-dev git python3-venv python3-pip python3-tk mesa-common-dev libglu1-mesa-dev freeglut3-dev cm-super 
      shell: bash
    
    - name: Bypass dgdepfixers problems - Ubuntu
      run: |
        mv $HOME/.profile $HOME/.profile_DISABLED  
        echo 'if [ -f $HOME/.bashrc ]; then . $HOME/.bashrc; fi' >> $HOME/.bash_profile
        git config --global user.name "Lorem Ipsum" 
        git config --global user.email "dolor.sit@ess.eu"
      shell: bash
    
    - name: cache dgdepfixer install
      id: cache-dgdepfixer
      uses: actions/cache@v2
      with:
        path: ~/dgdepfixerInstall
        key: ${{ inputs.runs-on }}-dgdepfixer-install
        
    - name: Create dgdepfixer
      run: touch alma.sh && echo "[ ! -d $HOME/dgdepfixerInstall ] &&  echo 'alma' " && . alma.sh
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1
        
    #run: [ ! -d $HOME/dgdepfixerInstall ] && ./$GITHUB_WORKSPACE/.github/scripts/dgdepfixer.sh --create -d $HOME/dgdepfixerInstall
        
  #  - name: cache Geant4
  #    id: cache-geant4
  #    uses: actions/cache@v2
  #    with:
  #      path: ~/geant4-10.04.p03
  #      key: ${{ matrix.os }}-Geant4--nodata-20211026
  #    shell: bash
  #      
  #  - name: Install Geant4
  #    run: |
  #      [ ! -d $HOME/geant4-10.04.p03 ] && . $HOME/dgdepfixerInstall/setup.sh 
  #      [ ! -d $HOME/geant4-10.04.p03 ] && dgdepfixer --instsw=Geant4 --nodata -d $HOME/geant4-10.04.p03
  #    shell: bash
      
