name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    required: true
  python-version:
    description: Python version to install
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - run: echo $PATH
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - run: echo $PATH
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ inputs.runs-on }}
      shell: bash
    - run: echo $PATH
    - name: Create dgdepfixer
      shell: bash
      run: |
        ls $GITHUB_WORKSPACE/.github/scripts
        chmod +x $GITHUB_WORKSPACE/.github/scripts/dgdepfixer
        $GITHUB_WORKSPACE/.github/scripts/dgdepfixer --create -d $HOME/dgdepfixerInstall
      env:
        DGDEP_IGNOREBADSHEBANG: 1
        
    - name: build dgcode
      run: |
        . $HOME/dgdepfixerInstall/setup.sh
        . bootstrap.sh
        dgbuild -a
      working-directory: dg_dgcode
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1

