name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    required: true
runs:
  using: "composite"
  steps:
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ inputs.runs-on }}
      shell: bash
      
    - name: Create dgdepfixer
      shell: bash
      run: |
        ls $GITHUB_WORKSPACE/.github/scripts
        chmod +x $GITHUB_WORKSPACE/.github/scripts/dgdepfixer
        $GITHUB_WORKSPACE/.github/scripts/dgdepfixer --create -d $HOME/dgdepfixerInstall
      env:
        DGDEP_IGNOREBADSHEBANG: 1
        
    - name: build dgcode
      run: |
        . $HOME/dgdepfixerInstall/setup.sh
        . bootstrap.sh
        dgbuild -a
      working-directory: dg_dgcode
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1

