name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  build-flag:
    description: build flag (e.g. 'debug' or 'release')
    type: string
    default: examine
runs:
  using: "composite"
  steps:
    - name: get OS version for caches
      id: os-version
      uses: sersoft-gmbh/os-version-action@v1
      
    - name: print os version
      run: |
        echo ${{ inputs.runs-on }}
        echo ${{ runner.os }}-${{ steps.os-version.outputs.version }}
      shell: bash
      
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ runner.os }}
      shell: bash
      
    - name: Create dgdepfixer
      run: |
        chmod +x $GITHUB_WORKSPACE/.github/scripts/dgdepfixer
        $GITHUB_WORKSPACE/.github/scripts/dgdepfixer --create -d $HOME/dgdepfixerInstall
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash
        
    - name: build dgcode
      run: |
        . $HOME/dgdepfixerInstall/setup.sh
        . bootstrap.sh
        dgbuild -a --${{ inputs.build-flag }}
      working-directory: dg_dgcode
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash

