name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  runs-on:
    description: Platform to execute on
    type: string
    required: true

runs:
  using: "composite"
  steps:
  
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ inputs.runs-on }}
      shell: bash
    
    - name: cache dgdepfixer install
      id: cache-dgdepfixer
      uses: actions/cache@v2
      with:
        path: ~/dgdepfixerInstall
        key: ${{ inputs.runs-on }}-dgdepfixer-install
     
    - name: Create dgdepfixer
      shell: bash
      run: eval 'if [ ! -d $HOME/dgdepfixerInstall ]; then ./$GITHUB_WORKSPACE/.github/scripts/dgdepfixer.sh --create -d $HOME/dgdepfixerInstall; fi'
    
    - name: cache Geant4
      id: cache-geant4
      uses: actions/cache@v2
      with:
        path: ~/geant4-10.04.p03
        key: ${{ inputs.runs-on }}-Geant4--nodata-20211026
        
    - name: Install Geant4
      run: |
        eval 'if [ ! -d $HOME/geant4-10.04.p03 ]; then . $HOME/dgdepfixerInstall/setup.sh; fi '
        eval 'if [ ! -d $HOME/geant4-10.04.p03 ]; then dgdepfixer --instsw=Geant4 --nodata -d $HOME/geant4-10.04.p03; fi'
      shell: bash
      
    - name: cache untarred geant4 data files
      id: cache-untarred-geant4-data-files
      uses: actions/cache@v2
      with:
        path: ~/Geant4data
        key: untarred-geant4-data-files 
 
    - name: Download Geant4 data
      run: eval 'if [ ! -d $HOME/Geant4data ]; then ./$GITHUB_WORKSPACE/.github/scripts/geant4DataProvider.sh; fi '
      shell: bash
      
    - name: build dgcode
      run: |
        . $HOME/dgdepfixerInstall/setup.sh
        . $HOME/geant4-10.04.p03/setup.sh
        . $GITHUB_WORKSPACE/.github/scripts/geant4DataSetup.sh
        . bootstrap.sh
        dgbuild -a
      working-directory: dg_dgcode
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1

