name: 'dgbuild'
description: 'Builds dgcode'
inputs:
  build-flag:
    description: build flag (e.g. 'debug' or 'release')
    type: string
    default: examine

runs:
  using: "composite"
  steps:
    - name: get OS version for caches
      id: os-version
      uses: sersoft-gmbh/os-version-action@v1
      
    - name: which Python
      run: python3 -V
      shell: bash
  
    - name: Install basic Prerequisites
      run: . $GITHUB_WORKSPACE/.github/scripts/instalPrerequisites.sh ${{ runner.os }}
      shell: bash
    
    - name: cache dgdepfixer install
      id: cache-dgdepfixer
      uses: actions/cache@v2
      with:
        path: ~/dgdepfixerInstall
        key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{env.CC}}-dgdepfixer-install
     
    - name: Create dgdepfixer
      run: | 
        eval 'if [ ! -d $HOME/dgdepfixerInstall ]; then chmod +x $GITHUB_WORKSPACE/.github/scripts/dgdepfixer ; fi'
        eval 'if [ ! -d $HOME/dgdepfixerInstall ]; then $GITHUB_WORKSPACE/.github/scripts/dgdepfixer --create -d $HOME/dgdepfixerInstall ; fi'
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash
      
    - name: cache Geant4
      id: cache-geant4
      uses: actions/cache@v2
      with:
        path: ~/geant4-10.04.p03
        key: ${{ runner.os }}-${{ steps.os-version.outputs.version }}-${{env.CC}}-Geant4--nodata
        
    - name: Install Geant4
      run: |
        eval 'if [ ! -d $HOME/geant4-10.04.p03 ]; then . $HOME/dgdepfixerInstall/setup.sh; fi '
        eval 'if [ ! -d $HOME/geant4-10.04.p03 ]; then dgdepfixer --instsw=Geant4 --nodata -d $HOME/geant4-10.04.p03; fi'
      env:
        DGDEP_IGNOREBADSHEBANG: 1
      shell: bash
      
    - name: cache untarred geant4 data files
      id: cache-untarred-geant4-data-files
      uses: actions/cache@v2
      with:
        path: ~/Geant4data
        key: untarred-geant4-data-files 
 
    - name: Download Geant4 data
      run: |
        eval 'if [ ! -d $HOME/Geant4data ]; then chmod +x $GITHUB_WORKSPACE/.github/scripts/geant4DataProvider.sh; fi '
        eval 'if [ ! -d $HOME/Geant4data ]; then $GITHUB_WORKSPACE/.github/scripts/geant4DataProvider.sh; fi '
      shell: bash
      
    - name: build dgcode
      run: |
        . $HOME/dgdepfixerInstall/setup.sh
        . $HOME/geant4-10.04.p03/setup.sh
        . $GITHUB_WORKSPACE/.github/scripts/geant4DataSetup.sh
        . bootstrap.sh
        dgbuild -a --${{ inputs.build-flag }}
      working-directory: dg_dgcode
      shell: bash
      env:
        DGDEP_IGNOREBADSHEBANG: 1

