name: 'dev_runValidationTests'

on:
  workflow_dispatch:
  
  schedule:
    - cron: '30 23 * * 0'  # 23:30 every Sunday
    
  #push:
  #  branches: [ main ]
  
  # Allows external webhook trigger
  #repository_dispatch:
  #  types: [framework-push]

jobs:
  validation-test:
    name: ${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}.dgcode-${{ matrix.build-flag }}
    strategy:
      fail-fast: false
      matrix: 
        include:
          # Ubuntu-20.04
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: '3.8', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: '3.8', build-flag: release, can-fail: false }
          
          - { os: ubuntu-20.04, CC: gcc-9,    CXX: g++-9,      python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-9,    CXX: g++-9,      python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-9,    CXX: g++-9,      python: '3.8', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: gcc-9,    CXX: g++-9,      python: '3.8', build-flag: release, can-fail: false }
          
          - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: '3.8', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: '3.8', build-flag: release, can-fail: false }
           
          - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: '3.8', build-flag: examine, can-fail: false }
          - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: '3.8', build-flag: release, can-fail: false }
         
          # Ubuntu-18.04
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: '3.6', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: '3.6', build-flag: release, can-fail: false }
           
          - { os: ubuntu-18.04, CC: gcc-7,    CXX: g++-7,      python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: gcc-7,    CXX: g++-7,      python: '3.9', build-flag: release, can-fail: true }
          - { os: ubuntu-18.04, CC: gcc-7,    CXX: g++-7,      python: '3.6', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: gcc-7,    CXX: g++-7,      python: '3.6', build-flag: release, can-fail: true }
          
          - { os: ubuntu-18.04, CC: gcc-10,   CXX: g++-10,     python: '3.9', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: gcc-10,   CXX: g++-10,     python: '3.9', build-flag: release, can-fail: false }
          - { os: ubuntu-18.04, CC: gcc-10,   CXX: g++-10,     python: '3.6', build-flag: examine, can-fail: false }
          - { os: ubuntu-18.04, CC: gcc-10,   CXX: g++-10,     python: '3.6', build-flag: release, can-fail: false }
          
          # macOS 10.15
          - { os: macos-10.15,  CC: clang,    CXX: clang++,    python: default, build-flag: examine, can-fail: false }
          - { os: macos-10.15,  CC: clang,    CXX: clang++,    python: default, build-flag: release, can-fail: false }
          
          # macOS 11
          - { os: macos-11,     CC: clang,    CXX: clang++,    python: default, build-flag: examine, can-fail: false }
          - { os: macos-11,     CC: clang,    CXX: clang++,    python: default, build-flag: release, can-fail: false }
          
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.can-fail }} 
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}
      PROJECTS_DIR: projects

    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout dgcode_validation
        uses: actions/checkout@v2
        with:
          repository: MilanKlausz/dgcode_validation
          path: './dgcode_validation'

      - name: setup framework action
        id: setup-framework
        uses: ./.github/actions/setup
        with:
          PYTHON_VERSION: ${{ matrix.python }}
          PROJECTS_DIR: ${{ env.PROJECTS_DIR }}
          DGBUILD_FLAG: ${{ matrix.build-flag }}
         
      - name: test dgcode
        run: |
          . $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
          . $GITHUB_WORKSPACE/geant4-10.04.p03/setup.sh
          . $GITHUB_WORKSPACE/.github/scripts/geant4DataSetup.sh
          . bootstrap.sh
          dgbuild -at --${{ matrix.build-flag }}
        working-directory: ${{ env.PROJECTS_DIR }}
        env:
          DGDEP_IGNOREBADSHEBANG: 1

      # - name: DEBUG ess_ncrystalreltests_testnamedmat
      #   if: always() #previous step fails if tests fail
      #   run: |
      #     . $GITHUB_WORKSPACE/dgdepfixerInstall/setup.sh
      #     . $GITHUB_WORKSPACE/geant4-10.04.p03/setup.sh
      #     . $GITHUB_WORKSPACE/.github/scripts/geant4DataSetup.sh
      #     . bootstrap.sh
      #     ess_ncrystalreltests_testnamedmat
      #   working-directory: ${{ env.PROJECTS_DIR }}
      #   env:
      #     DGDEP_IGNOREBADSHEBANG: 1

      - name: Rename test result
        id: rename-test-result
        if: always() && steps.setup-framework.outcome == 'success'
        run: mv $GITHUB_WORKSPACE/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat.xml $GITHUB_WORKSPACE/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat_${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}.dgcode-${{ matrix.build-flag }}.xml

      - uses: actions/upload-artifact@v2  # upload test results
        if: always() && steps.rename-test-result.outcome == 'success'
        with:
          name: test-results
          path: ${{ github.workspace }}/${{ env.PROJECTS_DIR }}/.bld/testresults/dgtest_results_junitformat_${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}.dgcode-${{ matrix.build-flag }}.xml

  report:
    name: Test reporting
    if: always()
    needs: validation-test
    runs-on: ubuntu-latest
    steps:
    # - uses: phoenix-actions/test-reporting@v3
    #   id: test-report                     # Set ID reference for step
    #   with:
    #     artifact: test-results           # artifact name
    #     name: JEST Tests                  # Name of the check run which will be created
    #     path: '*.xml'                     # Path to test results (inside artifact .zip)
    #     reporter: jest-junit              # Format of test results

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: test-results
        path: artifact_dir

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifact_dir

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # run even if the previous step fails
      with:
        check_name: JUnit Test Report
        report_paths: artifact_dir/dgtest_results_junitformat*.xml
  
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        check_name: EnricoMi Test Report
        files: artifact_dir/dgtest_results_junitformat*.xml
        report_individual_runs: true

    # - name: Test Report
    #   uses: dorny/test-reporter@v1
    #   if:  always() # run even if the previous step fails
    #   with:
    #     name: JEST Test Report 
    #     path: artifact_dir/dgtest_results_junitformat*.xml
    #     reporter: jest-junit # Format of test results