# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
        #working-directory: todo
    env:
      SHELL: /usr/bin/bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Test acces to the repo
        run: tail testFile
    
      - name: Install basic prerequisites
        run: sudo apt-get install curl g++ build-essential python3-dev cmake libxerces-c-dev libexpat1-dev gfortran libhdf5-serial-dev git python3-venv python3-pip python3-tk mesa-common-dev libglu1-mesa-dev freeglut3-dev cm-super

      - name: Download dgdepfixer
        run: curl -OSsf http://tkittel.web.cern.ch/tkittel/depfix/dgdepfixer && chmod +x ./dgdepfixer
    
      - name: cat .profile
        run: cat /home/runner/.profile
        
      - name: disable .profile
        run: mv /home/runner/.profile /home/runner/.profile_DISABLED
        
      - name: cat .profile
        run: cat ~/.bashrc
        
      - name: add .bashrc to bash_profile
        run: echo 'if [ -f $HOME/.bashrc ]; then . $HOME/.bashrc; fi' >> /home/runner/.bash_profile
        
      - name: Install dgdepfixer
        run: ./dgdepfixer
    
