name: testCommands

on:
  workflow_call:
    outputs:
      run_id:
        description: "run_id"
        value: ${{ GITHUB_RUN_ID }}
  workflow_dispatch:
jobs:
  blank:

    #runs-on: macos-10.15
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    #- uses: actions/checkout@v2
    #- name: get number of cpu-s
    #  run: sysctl -n hw.ncpu
    #- name: env
    #  run: env
    - name: blank
      run: echo "apple"
