name: testCommands

on:
  workflow_call:
    outputs:
      run-id:
        description: "run-id"
        value: ${{ jobs.echo-run-id.outputs.run-id }}
       # value: ${{ GITHUB_RUN_ID }}
  workflow_dispatch:
jobs:
  echo-run-id:
    outputs:
      run-id : ${{ steps.echo-step.outputs.runid }}
    #runs-on: macos-10.15
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    #- uses: actions/checkout@v2
    #- name: get number of cpu-s
    #  run: sysctl -n hw.ncpu
    #- name: env
    #  run: env
    - id: print-step
      run: echo ${{ env.GITHUB_RUN_ID }}
      
    - id: echo-step
      run: echo "::set-output name=runid::${{ env.GITHUB_RUN_ID }}"
