name: Report test results

on:
  workflow_dispatch:

  workflow_run:
    workflows: ['dev_runValidationTests']  # runs after dev_runValidationTests.yml workflow
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
    # - uses: phoenix-actions/test-reporting@v3
    #   id: test-report                     # Set ID reference for step
    #   with:
    #     artifact: test-results           # artifact name
    #     name: JEST Tests                  # Name of the check run which will be created
    #     path: '*.xml'                     # Path to test results (inside artifact .zip)
    #     reporter: jest-junit              # Format of test results

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: artifact_dir

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: artifact_dir

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # run even if the previous step fails
      with:
        check_name: JUnit Test Report
        report_paths: artifact_dir/dgtest_results_junitformat.xml