name: testCommands

on:
  # workflow_call:
  #   outputs:
  #     run-id:
  #       description: "run-id"
  #      # value: ${{ jobs.echo-run-id.outputs.run-id }}
  #      # value: ${{ github.run_id }}
  #       value: 5
  workflow_dispatch:
jobs:
  macos-cpu:
    runs-on: macos-10.15
    #runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    - name: get number of cpu-s
      run: | 
        system_profiler SPHardwareDataType
        sysctl -n hw.ncpu

  ubuntu-cpu:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    
    steps:
    - name: get number of cpu-s
      run: | 
        lscpu
        lscpu | egrep 'Model name|Socket|Thread|NUMA|CPU\(s\)'
