# This is a basic workflow to help you get started with Actions

name: Framework Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  jobs1:
    runs-on: ubuntu-20.04
    
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: echo variables
        run: |
          echo ${{ matrix.os }}
          echo ${{ runner.os }}
          echo $HOME
          echo $GITHUB_WORKSPACE

      - name: ls HOME and GITHUB_WORKSPACE
        run: |
          ls $HOME
          echo "----------------"
          ls $GITHUB_WORKSPACE

      - id: foo
        name: use the Action
        uses: ./.github/actions/firstTest
        with:
          runs-on: ${{ runner.os }}

      - name: ls HOME and GITHUB_WORKSPACE
        run: |
          ls $HOME
          echo "----------------"
          ls $GITHUB_WORKSPACE
