name: Test commands

on:
  workflow_dispatch:
jobs:
  build:

    runs-on: macos-10.15
    defaults:
      run:
        shell: bash
    
    steps:
    - uses: actions/checkout@v2
    - name: get number of cpu-s
      run: sysctl -n hw.ncpu
    - name: env
      run: env
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
