name: Test Compiller Matrix

on:
  workflow_dispatch:
  #push:
  #  branches: [ main ]

jobs:

  Linux:
    name: ${{ matrix.os }}.${{ matrix.CC }}.python-${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.10 }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.9 }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.8 }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.7 }
          - { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.6 }
          #- { os: ubuntu-20.04, CC: gcc-10,   CXX: g++-10,     python: 3.7 }
          #
          #- { os: ubuntu-20.04, CC: gcc-9,   CXX: g++-9,     python: 3.9 }
          #- { os: ubuntu-20.04, CC: gcc-9,   CXX: g++-9,     python: 3.7 }
         # 
         # - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: 3.9 }
         # - { os: ubuntu-20.04, CC: clang-10, CXX: clang++-10, python: 3.7 }
        # 
        #  - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: 3.9 }
         # - { os: ubuntu-20.04, CC: clang-12, CXX: clang++-12, python: 3.7 }
          
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: 3.10 }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: 3.9 }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: 3.8 }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: 3.7 }
          - { os: ubuntu-18.04, CC: clang-9,  CXX: clang++-9,  python: 3.6 }
          - { os: macos-10.15, CC: AppleXcode, CXX: AppleXcode }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash
      CC: ${{ matrix.CC }}
      CXX: ${{ matrix.CXX }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
  

      - name: dgbuild framework action
        uses: ./.github/actions/dgbuild-vanilla
        with:
          runs-on: ${{ matrix.os }}

      - name: test dgcode
        run: |
          . $HOME/dgdepfixerInstall/setup.sh
          . bootstrap.sh
          dgbuild -t
        working-directory: dg_dgcode
        env:
          DGDEP_IGNOREBADSHEBANG: 1
          
  macOS:
    name: ${{ matrix.os }}.python-${{ matrix.python }}
    strategy:
      fail-fast: false
      matrix: 
        include:
          - { os: macos-10.15, python: 3.10 }
          - { os: macos-10.15, python: 3.9 }
          - { os: macos-10.15, python: 3.8 }
          - { os: macos-10.15, python: 3.7 }
          - { os: macos-10.15, python: 3.7 }
          #- { os: macos-11 }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      SHELL: /bin/bash
      
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: dgbuild framework action
        uses: ./.github/actions/dgbuild-vanilla
        with:
          runs-on: ${{ matrix.os }}

      - name: test dgcode
        run: |
          . $HOME/dgdepfixerInstall/setup.sh
          . bootstrap.sh
          dgbuild -t
        working-directory: dg_dgcode
        env:
          DGDEP_IGNOREBADSHEBANG: 1
