name: testCommands

on:
  workflow_call:
    outputs:
      run_id:
        description: "run_id"
        value: ${{ jobs.echo-job-id.outputs.job-id }}
       # value: ${{ GITHUB_RUN_ID }}
  workflow_dispatch:
jobs:
  echo-job-id:
    outputs:
      job-id : ${{ steps.echo-step.outputs.jobid }}
    #runs-on: macos-10.15
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    
    steps:
    #- uses: actions/checkout@v2
    #- name: get number of cpu-s
    #  run: sysctl -n hw.ncpu
    #- name: env
    #  run: env
    - id: echo-step
      run: echo "::set-output name=jobid::hello"
